[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
 
[[redirects]]
	from = "/bir"
	to = "https://forms.gle/gheDfqiMNFwExHhz9"
	
[[redirects]]
	from = "/pple"
	to = "https://www.ox.ac.uk"
	
[[redirects]]
	from = "/llbbir"
	to = ""

[[redirects]]
	from = "/slides"
	to = "https://www.dropbox.com/scl/fi/0lw9c7v5aytzkwbxb5rub/1.-Introductions.pptx?rlkey=c2khxp5rwsozxdzq30sbyey08&dl=0"
	

[[redirects]]
	from = "/mid"	
	https://docs.google.com/forms/d/e/1FAIpQLSdDdMwJxGOcZ2a31DWaBEIid_KJFzEZhSKkzejcnlQxZibWMw/viewform?usp=sf_link

