[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
 
[[redirects]]
	from = "/bir"
	to = "https://www.dropbox.com/scl/fi/9kc2485bgu4zb3bj70dmh/malis.zip?rlkey=6ci3hj7up1di5ji77grp9it63&dl=0"
	
[[redirects]]
	from = "/pple"
	to = "https://docs.google.com/forms/d/e/1FAIpQLSfwCX3CCgNkRWGfvJrnU3dC-FIaq1cqj4eXJ_WYF-BZniEWqQ/viewform?usp=sf_link"
	
[[redirects]]
	from = "/llbbir"
	to = "https://docs.google.com/forms/d/e/1FAIpQLSdhHM_WYf-vFlCWwqCk729iVWLEEULsV-nxtVvyBmwNOrgpVg/viewform?usp=sf_link"
	
[[redirects]]
	from = "/mid"	
	to = "https://docs.google.com/forms/d/e/1FAIpQLSdDdMwJxGOcZ2a31DWaBEIid_KJFzEZhSKkzejcnlQxZibWMw/viewform?usp=sf_link"

[[redirects]]
	from = "/cycles"	
	to = "https://www.dropbox.com/scl/fi/c6sp820a5u3aj400y9ygg/polburcycles_slides.pdf?rlkey=kjjwde3293u83c0bhl95wi9c3&dl=0"

[[redirects]]
	from = "/slides"
	to = "https://www.dropbox.com/scl/fi/5ad1unjnmyg3ws9tmzr1y/3.-The-nature-formation-and-development-of-states.pptx?rlkey=6jr0vedt1kwwzjwgn361n8oyo&dl=0"
